python parse_xml_just_eyes.py --input /Volumes/MacBackup/ml_datasets/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_train.xml --output /Volumes/MacBackup/ml_datasets/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_train_eyes.xml
python parse_xml_just_eyes.py --input /Volumes/MacBackup/ml_datasets/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_test.xml --output /Volumes/MacBackup/ml_datasets/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_test_eyes.xml

